/**
 * POST /api/sensors/alert-trigger
 *
 * Called by the SENSORS page when a live IoT sensor reading exceeds a danger threshold.
 * Idempotent — uses a 30-minute window per sensor to prevent duplicate incidents.
 *
 * Body: {
 *   sensorCode: string
 *   sensorName: string
 *   value: number
 *   unit: string
 *   alertLevel: "WARNING" | "CRITICAL"
 *   type: string        // e.g. "H2S_DETECTOR", "GAS_LEL", "TEMPERATURE"
 *   siteId?: string
 * }
 */

import { NextRequest }   from "next/server";
import { auth }          from "@/auth";
import { ok, fail }      from "@/lib/api-response";
import { db }            from "@/lib/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SYSTEM_REPORTER_ID = "user-admin-001";

async function sendWhatsApp(message: string) {
  const phone  = process.env.CALLMEBOT_PHONE;
  const apiKey = process.env.CALLMEBOT_APIKEY;
  if (!phone || !apiKey) return;
  const encoded = encodeURIComponent(message);
  fetch(`https://api.callmebot.com/whatsapp.php?phone=${phone}&text=${encoded}&apikey=${apiKey}`)
    .catch(() => {});
}

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user) return fail("UNAUTHORIZED", "Sign in required", 401);

  let body: {
    sensorCode: string;
    sensorName: string;
    value: number;
    unit: string;
    alertLevel: string;
    type: string;
    siteId?: string;
  };

  try { body = await req.json(); }
  catch { return fail("INVALID_BODY", "Invalid JSON", 400); }

  if (!body.sensorCode || !body.value || !body.alertLevel) {
    return fail("MISSING_FIELDS", "sensorCode, value, alertLevel required", 400);
  }

  // Only act on WARNING or CRITICAL
  if (!["WARNING", "CRITICAL"].includes(body.alertLevel)) {
    return ok({ skipped: true, reason: "Not an alert level" });
  }

  // 30-minute idempotency window
  const windowKey = `iot-${body.sensorCode}-${Math.floor(Date.now() / (30 * 60 * 1000))}`;
  const existing  = await db.incident.findFirst({ where: { idempotencyKey: windowKey } });
  if (existing) {
    return ok({ skipped: true, reason: "Incident already created in this window", incidentId: existing.id });
  }

  // Resolve siteId
  let siteId = body.siteId ?? null;
  if (!siteId) {
    const first = await db.site.findFirst({ orderBy: { createdAt: "asc" } });
    siteId = first?.id ?? null;
  }
  if (!siteId) return fail("NO_SITE", "No site found to attach incident", 500);

  // Resolve reporter
  const reporter = await db.user.findFirst({
    where: { OR: [{ id: SYSTEM_REPORTER_ID }, { role: "ADMIN" }] },
    orderBy: { createdAt: "asc" },
  });
  const reporterId = reporter?.id ?? SYSTEM_REPORTER_ID;

  const incidentCount  = await db.incident.count();
  const incidentNumber = `INC-${new Date().getFullYear()}-${String(incidentCount + 1).padStart(4, "0")}`;

  const icon     = body.alertLevel === "CRITICAL" ? "🚨" : "⚠️";
  const severity = body.alertLevel === "CRITICAL" ? "HIGH" : "MEDIUM";

  const title = `${icon} ${body.alertLevel} Sensor Reading — ${body.sensorCode} (${body.value} ${body.unit})`;
  const description =
    `Auto-detected by AEGIS IoT monitoring. Sensor ${body.sensorCode} (${body.sensorName}) ` +
    `reported a ${body.alertLevel.toLowerCase()} reading of ${body.value} ${body.unit}. ` +
    `Sensor type: ${body.type}.`;

  const incident = await db.incident.create({
    data: {
      incidentNumber,
      idempotencyKey: windowKey,
      title,
      description,
      type:           "PROCESS_SAFETY",
      severity,
      status:         "REPORTED",
      location:       `IoT Sensor: ${body.sensorCode}`,
      occurredAt:     new Date(),
      isAutoEscalated: true,
      siteId,
      reporterId,
    },
  });

  // Add notes as action
  await db.incidentAction.create({
    data: {
      incidentId:      incident.id,
      description:     `📡 Sensor reading details:\n• Sensor: ${body.sensorCode} — ${body.sensorName}\n• Type: ${body.type}\n• Reading: ${body.value} ${body.unit}\n• Alert level: ${body.alertLevel}\n• Detected at: ${new Date().toISOString()}\n• Auto-created by AEGIS sensor monitoring`,
      status:          "PENDING",
      isAutoGenerated: true,
    },
  });

  // Auto-create a follow-up Task
  const dueDate = new Date(Date.now() + 2 * 60 * 60 * 1000); // 2 hours from now
  await db.task.create({
    data: {
      title:          `${icon} Follow-up: ${body.sensorCode} — ${body.value} ${body.unit}`,
      description:    `Auto-generated from sensor alert.\n` +
                      `Sensor: ${body.sensorCode} (${body.sensorName})\n` +
                      `Type: ${body.type} | Reading: ${body.value} ${body.unit} | Level: ${body.alertLevel}\n` +
                      `Incident: ${incidentNumber} — Verify area, check sensor, and confirm safe.`,
      category:       "INCIDENT_FOLLOWUP",
      priority:       severity === "HIGH" ? "CRITICAL" : "HIGH",
      status:         "PENDING",
      isAutoAssigned: true,
      dueDate,
      siteId,
    },
  }).catch(() => {});

  // Audit
  await db.auditLog.create({
    data: {
      action:      "AUTO_INCIDENT_CREATED",
      module:      "SENSORS",
      actionType:  "AUTONOMOUS",
      description: `Auto-created incident ${incidentNumber} from IoT sensor ${body.sensorCode}`,
      isAutonomous: true,
      metadata:    JSON.stringify({ sensorCode: body.sensorCode, value: body.value, unit: body.unit, alertLevel: body.alertLevel }),
    },
  }).catch(() => {});

  // WhatsApp
  const waMsg =
`${icon} AEGIS IoT SENSOR ALERT
━━━━━━━━━━━━━━━━━━━━
📡 Sensor: ${body.sensorCode}
📋 Name: ${body.sensorName}
🔬 Type: ${body.type}
📊 Reading: ${body.value} ${body.unit}
⚠️ Level: ${body.alertLevel}
━━━━━━━━━━━━━━━━━━━━
📝 Incident: ${incidentNumber}
🚨 ACTION REQUIRED
🤖 AEGIS Auto-Alert`;

  await sendWhatsApp(waMsg);

  return ok({ incident: { id: incident.id, number: incidentNumber }, notified: true });
}
