import { NextRequest, NextResponse } from "next/server";
import { ok, fail }                  from "@/lib/api-response";
import { db }                        from "@/lib/db";
import { requireScopedAuth }         from "@/lib/scoped-auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const scope = await requireScopedAuth();
  if (scope instanceof NextResponse) return scope;

  const { id } = await params;

  const investigation = await db.investigation.findUnique({
    where: { id },
    include: {
      incident: {
        select: {
          id: true, incidentNumber: true, title: true, description: true,
          type: true, severity: true, status: true, location: true,
          occurredAt: true, siteId: true, aiAnalysis: true,
          actions: {
            orderBy: { dueDate: "asc" },
            select: { id: true, description: true, status: true, dueDate: true, completedAt: true, isAutoGenerated: true },
          },
        },
      },
      leadInvestigator: { select: { id: true, name: true, role: true, department: true } },
    },
  });

  if (!investigation) return fail("NOT_FOUND", "Investigation not found", 404);
  if (!scope.canSee(investigation.incident.siteId)) return fail("NOT_FOUND", "Investigation not found", 404);

  return ok({ investigation });
}

export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const scope = await requireScopedAuth();
  if (scope instanceof NextResponse) return scope;

  const { id } = await params;

  let body: { status?: string; rootCause?: string; summary?: string; hasAIEvidence?: boolean };
  try { body = await req.json(); }
  catch { return fail("INVALID_BODY", "Invalid JSON", 400); }

  const existing = await db.investigation.findUnique({
    where: { id },
    include: { incident: { select: { siteId: true } } },
  });
  if (!existing) return fail("NOT_FOUND", "Investigation not found", 404);
  if (!scope.canSee(existing.incident.siteId)) return fail("NOT_FOUND", "Investigation not found", 404);

  const data: Record<string, unknown> = {};
  if (body.status        !== undefined) data.status        = body.status;
  if (body.rootCause     !== undefined) data.rootCause     = body.rootCause;
  if (body.summary       !== undefined) data.summary       = body.summary;
  if (body.hasAIEvidence !== undefined) data.hasAIEvidence = body.hasAIEvidence;

  const updated = await db.investigation.update({ where: { id }, data });
  return ok({ investigation: updated });
}
