"use client";

import { type ReactNode, useCallback, useEffect, useState } from "react";
import { useParams }                        from "next/navigation";
import Link                                  from "next/link";
import {
  ArrowLeft, Brain, Loader2, CheckCircle2, Clock, AlertTriangle,
  ChevronDown, ChevronUp, Pencil, Save, X, RotateCcw,
} from "lucide-react";
import { cn } from "@/lib/utils";

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

interface Why {
  level:    number;
  question: string;
  answer:   string;
}

interface BowTie {
  threats:      string[];
  topEvent:     string;
  consequences: string[];
  barriers:     string[];
}

interface AIAnalysis {
  whys:                       Why[];
  rootCause:                  string;
  contributingFactors:        string[];
  immediateCorrectiveActions: string[];
  systemicPreventiveActions:  string[];
  riskLevel:                  string;
  bowTie:                     BowTie;
  summary:                    string;
}

interface IncidentAction {
  id:             string;
  description:    string;
  status:         string;
  dueDate:        string | null;
  completedAt:    string | null;
  isAutoGenerated:boolean;
}

interface Investigation {
  id:            string;
  status:        string;
  rootCause:     string | null;
  summary:       string | null;
  hasAIEvidence: boolean;
  createdAt:     string;
  updatedAt:     string;
  leadInvestigator: { id: string; name: string; role: string; department: string | null };
  incident: {
    id:             string;
    incidentNumber: string;
    title:          string;
    description:    string;
    type:           string;
    severity:       string;
    status:         string;
    location:       string;
    occurredAt:     string;
    aiAnalysis:     string | null;
    actions:        IncidentAction[];
  };
}

// ─────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────

const SEV_BADGE: Record<string, string> = {
  LOW:      "border-green-500/40  bg-green-500/10  text-green-400",
  MEDIUM:   "border-yellow-500/40 bg-yellow-500/10 text-yellow-400",
  HIGH:     "border-orange-500/40 bg-orange-500/10 text-orange-400",
  CRITICAL: "border-red-500/40    bg-red-500/10    text-red-400",
};
const STATUS_FLOW: Record<string, string> = {
  OPEN:      "IN_REVIEW",
  IN_REVIEW: "CLOSED",
};
const STATUS_LABEL: Record<string, string> = {
  OPEN:      "Mark In Review",
  IN_REVIEW: "Close Investigation",
};

// ─────────────────────────────────────────────────────────────
// Page
// ─────────────────────────────────────────────────────────────

export default function InvestigationDetailPage() {
  const params   = useParams<{ id: string }>();
  const id       = params.id;

  const [inv,         setInv]         = useState<Investigation | null>(null);
  const [analysis,    setAnalysis]    = useState<AIAnalysis | null>(null);
  const [loading,     setLoading]     = useState(true);
  const [running,     setRunning]     = useState(false);
  const [advancing,   setAdvancing]   = useState(false);

  // Edit root cause
  const [editing,   setEditing]   = useState(false);
  const [editVal,   setEditVal]   = useState("");
  const [saving,    setSaving]    = useState(false);

  // Collapsible sections
  const [showActions,  setShowActions]  = useState(false);
  const [showWhys,     setShowWhys]     = useState(true);
  const [showBowTie,   setShowBowTie]   = useState(false);

  const loadInv = useCallback(async () => {
    setLoading(true);
    const r = await fetch(`/api/investigations/${id}`);
    const j = await r.json();
    if (j.ok) {
      const data = j.data.investigation as Investigation;
      setInv(data);
      if (data.summary) {
        try { setAnalysis(JSON.parse(data.summary) as AIAnalysis); } catch { /* not JSON */ }
      }
    }
    setLoading(false);
  }, [id]);

  useEffect(() => { loadInv(); }, [loadInv]);

  async function runAnalysis() {
    if (!confirm("Run AEGIS AI 5-Whys analysis on this incident? This will overwrite any existing analysis.")) return;
    setRunning(true);
    const r = await fetch(`/api/investigations/${id}/analyze`, { method: "POST" });
    const j = await r.json();
    if (j.ok) {
      setAnalysis(j.data.analysis as AIAnalysis);
      setInv((prev) => prev ? { ...prev, hasAIEvidence: true, rootCause: j.data.analysis.rootCause, summary: JSON.stringify(j.data.analysis) } : prev);
      setShowWhys(true);
    } else {
      alert(j.error?.message ?? "Analysis failed");
    }
    setRunning(false);
  }

  async function advanceStatus() {
    if (!inv) return;
    const next = STATUS_FLOW[inv.status];
    if (!next) return;
    setAdvancing(true);
    const r = await fetch(`/api/investigations/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: next }),
    });
    const j = await r.json();
    if (j.ok) setInv((prev) => prev ? { ...prev, status: next } : prev);
    setAdvancing(false);
  }

  async function saveRootCause() {
    setSaving(true);
    const r = await fetch(`/api/investigations/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ rootCause: editVal }),
    });
    const j = await r.json();
    if (j.ok) {
      setInv((prev) => prev ? { ...prev, rootCause: editVal } : prev);
      setEditing(false);
    }
    setSaving(false);
  }

  if (loading) return (
    <div className="flex h-64 items-center justify-center gap-2 text-muted-foreground text-sm">
      <Loader2 className="h-4 w-4 animate-spin" /> Loading investigation…
    </div>
  );
  if (!inv) return (
    <div className="flex h-64 items-center justify-center text-muted-foreground text-sm">
      Investigation not found.
    </div>
  );

  const statusNext = STATUS_FLOW[inv.status];

  return (
    <div className="container mx-auto max-w-4xl px-6 py-6 space-y-5">

      {/* ── Back + Header ─────────────────────────────────── */}
      <div className="flex items-center gap-3">
        <Link href="/safety/investigations"
          className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> All Investigations
        </Link>
      </div>

      <div className="rounded-2xl border border-border/40 bg-background/60 p-5 space-y-3">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="space-y-1.5">
            <div className="flex flex-wrap items-center gap-2">
              <span className="font-mono text-xs text-muted-foreground">{inv.incident.incidentNumber}</span>
              <span className={cn("rounded border px-2 py-0.5 text-xs font-semibold", SEV_BADGE[inv.incident.severity])}>
                {inv.incident.severity}
              </span>
              <InvStatusBadge status={inv.status} />
              {inv.hasAIEvidence && (
                <span className="rounded border border-primary/40 bg-primary/10 px-2 py-0.5 text-xs text-primary flex items-center gap-1">
                  <Brain className="h-3 w-3" /> AI ANALYSED
                </span>
              )}
            </div>
            <h1 className="font-display text-xl leading-snug">{inv.incident.title}</h1>
            <p className="text-sm text-muted-foreground">
              📍 {inv.incident.location} &nbsp;·&nbsp; 📅 {new Date(inv.incident.occurredAt).toLocaleString("en-GB")}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {statusNext && (
              <button onClick={advanceStatus} disabled={advancing}
                className="flex items-center gap-1.5 rounded-lg border border-border/50 bg-muted/20 px-3 py-2 text-xs hover:border-primary/40 hover:text-primary disabled:opacity-50">
                {advancing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <ChevronUp className="h-3.5 w-3.5" />}
                {STATUS_LABEL[inv.status]}
              </button>
            )}
            <button onClick={runAnalysis} disabled={running}
              className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
              {running ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Brain className="h-3.5 w-3.5" />}
              {running ? "Analysing…" : "Run AI Analysis"}
            </button>
          </div>
        </div>

        {/* Incident description */}
        {inv.incident.description && (
          <p className="text-sm text-muted-foreground border-t border-border/30 pt-3">
            {inv.incident.description}
          </p>
        )}

        {/* Lead + dates */}
        <div className="flex flex-wrap gap-4 text-xs text-muted-foreground border-t border-border/30 pt-3">
          <span>🔍 Lead: <strong className="text-foreground">{inv.leadInvestigator.name}</strong> ({inv.leadInvestigator.role})</span>
          {inv.leadInvestigator.department && <span>🏢 {inv.leadInvestigator.department}</span>}
          <span>📅 Opened: {new Date(inv.createdAt).toLocaleString("en-GB")}</span>
          <span>🔄 Updated: {new Date(inv.updatedAt).toLocaleString("en-GB")}</span>
        </div>
      </div>

      {/* ── Root Cause ────────────────────────────────────── */}
      <Section title="Root Cause" icon="🎯">
        {editing ? (
          <div className="space-y-2">
            <textarea value={editVal} onChange={(e) => setEditVal(e.target.value)} rows={3}
              className="w-full rounded-lg border border-primary/40 bg-background px-3 py-2 text-sm focus:outline-none focus:border-primary resize-none" />
            <div className="flex gap-2">
              <button onClick={saveRootCause} disabled={saving}
                className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground disabled:opacity-50">
                {saving ? <Loader2 className="h-3 w-3 animate-spin" /> : <Save className="h-3 w-3" />} Save
              </button>
              <button onClick={() => setEditing(false)}
                className="flex items-center gap-1.5 rounded-lg border border-border/50 px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground">
                <X className="h-3 w-3" /> Cancel
              </button>
            </div>
          </div>
        ) : inv.rootCause ? (
          <div className="flex items-start justify-between gap-3">
            <p className="text-sm leading-relaxed">{inv.rootCause}</p>
            {inv.status !== "CLOSED" && (
              <button onClick={() => { setEditVal(inv.rootCause ?? ""); setEditing(true); }}
                className="shrink-0 text-muted-foreground hover:text-primary"><Pencil className="h-3.5 w-3.5" /></button>
            )}
          </div>
        ) : (
          <div className="text-sm text-muted-foreground italic space-y-2">
            No root cause recorded yet.
            <button onClick={() => { setEditVal(""); setEditing(true); }}
              className="ml-2 text-primary text-xs hover:underline">Add manually</button>
            <span className="ml-1 text-xs text-muted-foreground">or</span>
            <button onClick={runAnalysis} disabled={running}
              className="ml-1 text-primary text-xs hover:underline disabled:opacity-50">Run AI Analysis</button>
          </div>
        )}
      </Section>

      {/* ── AI Analysis: 5-Whys ───────────────────────────── */}
      {analysis && (
        <div className="rounded-2xl border border-primary/20 bg-primary/3 overflow-hidden">
          <button onClick={() => setShowWhys((v) => !v)}
            className="w-full flex items-center justify-between px-5 py-3.5 text-left hover:bg-primary/5 transition-colors">
            <span className="font-semibold text-sm flex items-center gap-2">
              <Brain className="h-4 w-4 text-primary" /> AI 5-Whys Analysis
              {analysis.riskLevel && (
                <span className={cn("rounded px-1.5 py-0.5 text-[10px] font-semibold",
                  analysis.riskLevel === "CRITICAL" ? "bg-red-500/20 text-red-400" :
                  analysis.riskLevel === "HIGH"     ? "bg-orange-500/20 text-orange-400" :
                  analysis.riskLevel === "MEDIUM"   ? "bg-yellow-500/20 text-yellow-400" : "bg-green-500/20 text-green-400"
                )}>{analysis.riskLevel} RISK</span>
              )}
            </span>
            {showWhys ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
          </button>

          {showWhys && (
            <div className="px-5 pb-5 space-y-4">
              {/* Summary */}
              {analysis.summary && (
                <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-muted-foreground">
                  {analysis.summary}
                </div>
              )}

              {/* 5-Whys timeline */}
              <div className="space-y-0">
                {analysis.whys.map((w, i) => (
                  <div key={i} className="relative pl-8">
                    {/* Connector line */}
                    {i < analysis.whys.length - 1 && (
                      <div className="absolute left-3.5 top-6 bottom-0 w-px bg-border/50" />
                    )}
                    {/* Node */}
                    <div className={cn(
                      "absolute left-0 top-3 flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold border-2",
                      i === analysis.whys.length - 1
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-border bg-background text-muted-foreground"
                    )}>
                      {w.level}
                    </div>
                    <div className={cn(
                      "mb-3 rounded-lg border px-4 py-3",
                      i === analysis.whys.length - 1
                        ? "border-primary/30 bg-primary/5"
                        : "border-border/40 bg-muted/10"
                    )}>
                      <div className="text-[10px] uppercase tracking-wide text-muted-foreground mb-0.5">{w.question}</div>
                      <div className="text-sm">{w.answer}</div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Contributing factors + Corrective actions grid */}
              <div className="grid sm:grid-cols-3 gap-3">
                <ListCard
                  title="Contributing Factors"
                  icon="⚠️"
                  items={analysis.contributingFactors}
                  tone="warn"
                />
                <ListCard
                  title="Immediate Actions"
                  icon="⚡"
                  items={analysis.immediateCorrectiveActions}
                  tone="info"
                />
                <ListCard
                  title="Systemic Prevention"
                  icon="🛡️"
                  items={analysis.systemicPreventiveActions}
                  tone="ok"
                />
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Bow-Tie Diagram ───────────────────────────────── */}
      {analysis?.bowTie && (
        <div className="rounded-2xl border border-border/40 overflow-hidden">
          <button onClick={() => setShowBowTie((v) => !v)}
            className="w-full flex items-center justify-between px-5 py-3.5 text-left hover:bg-muted/10 transition-colors">
            <span className="font-semibold text-sm flex items-center gap-2">🎀 Bow-Tie Risk Diagram</span>
            {showBowTie ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
          </button>
          {showBowTie && <BowTieDisplay bt={analysis.bowTie} />}
        </div>
      )}

      {/* ── Incident Actions / Evidence ───────────────────── */}
      {inv.incident.actions.length > 0 && (
        <div className="rounded-2xl border border-border/40 overflow-hidden">
          <button onClick={() => setShowActions((v) => !v)}
            className="w-full flex items-center justify-between px-5 py-3.5 text-left hover:bg-muted/10 transition-colors">
            <span className="font-semibold text-sm flex items-center gap-2">
              📋 Incident Actions / Evidence
              <span className="rounded bg-muted/50 px-1.5 py-0.5 text-[10px] text-muted-foreground">
                {inv.incident.actions.length}
              </span>
            </span>
            {showActions ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
          </button>
          {showActions && (
            <div className="px-5 pb-4 space-y-2">
              {inv.incident.actions.map((a) => (
                <div key={a.id} className="flex items-start gap-3 rounded-lg border border-border/30 bg-muted/5 px-3 py-2.5">
                  <ActionStatusIcon status={a.status} />
                  <div className="flex-1 min-w-0">
                    <div className="text-sm">{a.description}</div>
                    <div className="flex flex-wrap gap-2 mt-1 text-[10px] text-muted-foreground">
                      <span className={cn(
                        "rounded px-1.5 py-0.5 font-medium",
                        a.status === "COMPLETED" ? "bg-green-500/15 text-green-400" :
                        a.status === "IN_PROGRESS" ? "bg-primary/15 text-primary" : "bg-muted/30"
                      )}>{a.status.replace("_", " ")}</span>
                      {a.isAutoGenerated && <span className="rounded bg-amber-500/15 px-1.5 py-0.5 text-amber-400">AUTO</span>}
                      {a.dueDate && <span>Due {new Date(a.dueDate).toLocaleDateString("en-GB")}</span>}
                      {a.completedAt && <span>✅ {new Date(a.completedAt).toLocaleDateString("en-GB")}</span>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* ── No analysis prompt ────────────────────────────── */}
      {!analysis && !inv.hasAIEvidence && (
        <div className="rounded-2xl border border-dashed border-primary/30 bg-primary/3 py-8 text-center space-y-3">
          <div className="text-3xl">🤖</div>
          <div className="font-semibold text-sm">No AI analysis yet</div>
          <div className="text-xs text-muted-foreground max-w-sm mx-auto">
            Run the AEGIS AI 5-Whys analysis to automatically identify root causes, contributing factors, corrective actions, and a Bow-Tie risk diagram.
          </div>
          <button onClick={runAnalysis} disabled={running}
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
            {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Brain className="h-4 w-4" />}
            {running ? "Analysing…" : "Run AI Analysis"}
          </button>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Section wrapper
// ─────────────────────────────────────────────────────────────

function Section({ title, icon, children }: { title: string; icon: string; children: ReactNode }) {
  return (
    <div className="rounded-2xl border border-border/40 bg-background/60 px-5 py-4 space-y-3">
      <h2 className="font-semibold text-sm flex items-center gap-2">{icon} {title}</h2>
      {children}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// ListCard
// ─────────────────────────────────────────────────────────────

function ListCard({ title, icon, items, tone }: { title: string; icon: string; items: string[]; tone: "warn" | "info" | "ok" }) {
  const cls: Record<string, string> = {
    warn: "border-amber-500/30 bg-amber-500/5",
    info: "border-primary/30  bg-primary/5",
    ok:   "border-green-500/30 bg-green-500/5",
  };
  return (
    <div className={cn("rounded-xl border p-3 space-y-1.5", cls[tone])}>
      <div className="text-[10px] uppercase tracking-wide text-muted-foreground font-semibold">{icon} {title}</div>
      <ul className="space-y-1.5">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-1.5 text-xs text-foreground/90">
            <span className="mt-0.5 shrink-0 text-muted-foreground">·</span>
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Bow-Tie Display
// ─────────────────────────────────────────────────────────────

function BowTieDisplay({ bt }: { bt: BowTie }) {
  return (
    <div className="px-5 pb-5">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 items-start">
        {/* Threats */}
        <div className="space-y-2">
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold text-right">Threats / Causes</div>
          {bt.threats.map((t, i) => (
            <div key={i} className="rounded-lg border border-red-500/30 bg-red-500/8 px-3 py-2 text-xs text-right">
              {t}
            </div>
          ))}
        </div>

        {/* Central bow-tie */}
        <div className="flex flex-col items-center gap-3">
          <div className="rounded-xl border-2 border-primary bg-primary/10 px-4 py-3 text-center text-xs font-semibold leading-snug w-full">
            🎀 {bt.topEvent}
          </div>
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground text-center">Barriers / Controls</div>
          {bt.barriers.map((b, i) => (
            <div key={i} className="rounded-lg border border-green-500/30 bg-green-500/8 px-3 py-2 text-xs text-center w-full">
              🛡️ {b}
            </div>
          ))}
        </div>

        {/* Consequences */}
        <div className="space-y-2">
          <div className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold">Consequences</div>
          {bt.consequences.map((c, i) => (
            <div key={i} className="rounded-lg border border-orange-500/30 bg-orange-500/8 px-3 py-2 text-xs">
              {c}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Status Badge
// ─────────────────────────────────────────────────────────────

function InvStatusBadge({ status }: { status: string }) {
  const cls: Record<string, string> = {
    OPEN:      "bg-amber-500/15  text-amber-400",
    IN_REVIEW: "bg-primary/15    text-primary",
    CLOSED:    "bg-green-500/15  text-green-400",
  };
  return (
    <span className={cn("rounded px-2 py-0.5 text-xs font-medium", cls[status] ?? "bg-muted/30 text-muted-foreground")}>
      {status.replace("_", " ")}
    </span>
  );
}

// ─────────────────────────────────────────────────────────────
// Action status icon
// ─────────────────────────────────────────────────────────────

function ActionStatusIcon({ status }: { status: string }) {
  if (status === "COMPLETED")   return <CheckCircle2 className="mt-0.5 h-4 w-4 text-green-500 shrink-0" />;
  if (status === "IN_PROGRESS") return <RotateCcw   className="mt-0.5 h-4 w-4 text-primary shrink-0 animate-spin" style={{ animationDuration: "3s" }} />;
  return <Clock className="mt-0.5 h-4 w-4 text-muted-foreground shrink-0" />;
}
