"use client";

import { use, useState, useMemo } from "react";
import Link from "next/link";
import { useApi } from "@/hooks/use-api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  AlertTriangle, Brain, Loader2, CheckCircle2,
  MapPin, Clock, User, Clapperboard, Siren,
  ChevronRight, Shield, TrendingUp,
} from "lucide-react";
import { cn, timeAgo, formatDateTime, riskColor } from "@/lib/utils";
import { ShareInsightButton } from "@/components/knowledge/share-insight-button";
import type { ApiResponse } from "@/types";

interface Incident {
  id: string;
  incidentNumber: string;
  title: string;
  description: string;
  type: string;
  severity: string;
  status: string;
  location: string;
  occurredAt: string;
  reportedAt: string;
  resolvedAt: string | null;
  isAutoEscalated: boolean;
  aiAnalysis: AIAnalysis | string | null;
  site: { code: string; name: string; nameAr: string | null } | null;
  reporter: { name: string; role: string };
  assignee: { name: string; role: string } | null;
  actions: Array<{
    id: string;
    description: string;
    status: string;
    dueDate: string | null;
    completedAt: string | null;
    isAutoGenerated: boolean;
  }>;
}

interface AIAnalysis {
  rootCause?: string;
  contributingFactors?: string[];
  immediateActions?: string[];
  preventiveActions?: string[];
  riskLevel?: string;
  recommendations?: string[];
  summary?: string;
  similarRiskAreas?: string[];
  predictions?: string[];
}

interface VideoState {
  status: "IDLE" | "SUBMITTING" | "PROCESSING" | "DONE" | "ERROR";
  videoPrompt: string;
  videoUrl: string | null;
  predictionId: string | null;
  message: string;
  pollCount: number;
}

function parseAI(raw: unknown): AIAnalysis | null {
  if (!raw) return null;
  if (typeof raw === "string") {
    try { return JSON.parse(raw) as AIAnalysis; }
    catch { return null; }
  }
  if (typeof raw === "object") return raw as AIAnalysis;
  return null;
}

export default function IncidentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data: incident, loading, refresh } = useApi<Incident>(`/api/incidents/${id}`);

  const [analyzing, setAnalyzing] = useState(false);
  const [analyzeErr, setAnalyzeErr] = useState<string | null>(null);

  const [video, setVideo] = useState<VideoState>({
    status: "IDLE", videoPrompt: "", videoUrl: null,
    predictionId: null, message: "", pollCount: 0,
  });

  const ai = useMemo(() => parseAI(incident?.aiAnalysis), [incident?.aiAnalysis]);

  async function runAnalysis() {
    setAnalyzing(true);
    setAnalyzeErr(null);
    try {
      const res = await fetch(`/api/incidents/${id}/analyze`, {
        method: "POST", credentials: "include",
      });
      const json = (await res.json()) as ApiResponse<{ analysis: AIAnalysis }>;
      if (!json.ok) throw new Error(json.error?.message ?? "Analysis failed");
      refresh();
    } catch (err) {
      setAnalyzeErr(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setAnalyzing(false);
    }
  }

  async function generateVideo() {
    if (!incident) return;
    setVideo({
      status: "SUBMITTING", videoPrompt: "", videoUrl: null,
      predictionId: null, message: "Submitting...", pollCount: 0,
    });
    try {
      const res = await fetch("/api/ai/generate-video", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ incidentId: incident.id }),
      });
      const json = (await res.json()) as ApiResponse<{
        status: string; videoPrompt: string;
        predictionId: string | null; videoUrl: string | null; message: string;
      }>;
      if (!json.ok || !json.data) throw new Error(json.error?.message ?? "Submission failed");

      const { videoPrompt, predictionId, videoUrl, status } = json.data;
      if (!predictionId || status !== "PROCESSING") {
        setVideo({
          status: "DONE", videoPrompt, videoUrl, predictionId: null,
          message: json.data.message, pollCount: 0,
        });
        return;
      }

      setVideo((v) => ({
        ...v, status: "PROCESSING", videoPrompt,
        predictionId, message: "Generating video...",
      }));

      // Poll for up to 120 attempts × 5s = 10 minutes
      for (let i = 0; i < 120; i++) {
        await new Promise((r) => setTimeout(r, 5000));

        const pollRes = await fetch(`/api/ai/video-status/${predictionId}`, { credentials: "include" });
        const pollJson = (await pollRes.json()) as ApiResponse<{
          status: string; videoUrl: string | null; error?: string;
        }>;

        if (!pollJson.ok || !pollJson.data) {
          console.log(`[poll ${i}] not ok, retrying...`);
          continue;
        }

        const { status: pStatus, videoUrl: pUrl } = pollJson.data;
        const secs = (i + 1) * 5;
        const mins = Math.round(secs / 60);
        setVideo((v) => ({
          ...v, pollCount: i + 1,
          message: secs < 60 ? `Generating... ${secs}s` : `Generating... ~${mins} min`,
        }));

        if ((pStatus === "COMPLETED" || pStatus === "succeeded") && pUrl) {
          setVideo((v) => ({
            ...v, status: "DONE", videoUrl: pUrl,
            message: "Video ready!",
          }));
          fetch("/api/notify/whatsapp", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            credentials: "include",
            body: JSON.stringify({
              message: `*Training Video Ready*\nIncident: ${incident.title}\nSite: ${incident.site?.name ?? "N/A"}\nWatch: ${pUrl}\n_AEGIS HSSE Platform_`,
            }),
          }).catch(() => {});
          return;
        }

        if (pStatus === "FAILED" || pStatus === "failed") {
          throw new Error(pollJson.data.error ?? "Video generation failed");
        }
      }
      throw new Error("Timed out after 10 minutes");
    } catch (err) {
      setVideo((v) => ({
        ...v, status: "ERROR",
        message: err instanceof Error ? err.message : "Unknown error",
      }));
    }
  }

  if (loading) return (
    <div className="container mx-auto px-6 py-12 text-center">
      <Loader2 className="mx-auto h-6 w-6 animate-spin text-muted-foreground" />
    </div>
  );

  if (!incident) return (
    <div className="container mx-auto px-6 py-12 text-center text-sm text-muted-foreground">
      Incident not found.
    </div>
  );

  return (
    <div className="container mx-auto max-w-5xl px-6 py-8">
      {/* Breadcrumb */}
      <div className="mb-4 flex items-center gap-1.5 text-xs text-muted-foreground">
        <Link href="/safety/incidents" className="hover:text-foreground">Incidents</Link>
        <ChevronRight className="h-3 w-3" />
        <span className="text-foreground">{incident.incidentNumber}</span>
      </div>

      {/* Header */}
      <div className="mb-6">
        <div className="flex flex-wrap items-center gap-2">
          <span className={cn("rounded-full border px-2.5 py-0.5 text-[10px] font-bold uppercase", riskColor(incident.severity))}>
            {incident.severity}
          </span>
          <span className="num text-sm text-muted-foreground">{incident.incidentNumber}</span>
          {incident.isAutoEscalated && (
            <span className="rounded-full border border-primary/40 bg-primary/10 px-2 py-0.5 text-[10px] text-primary">
              Auto-escalated
            </span>
          )}
        </div>
        <div className="mt-2 flex items-start justify-between gap-3 flex-wrap">
          <h1 className="font-display text-3xl tracking-tight">{incident.title}</h1>
          <ShareInsightButton contextType="incident" contextId={incident.id} />
        </div>
        <div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-muted-foreground">
          <span className={cn(
            "rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase",
            incident.status === "RESOLVED" || incident.status === "CLOSED"
              ? "border-risk-low/40 bg-risk-low/10 text-risk-low"
              : incident.status === "INVESTIGATING"
                ? "border-risk-medium/40 bg-risk-medium/10 text-risk-medium"
                : "border-risk-high/40 bg-risk-high/10 text-risk-high",
          )}>
            {incident.status.replace(/_/g, " ")}
          </span>
          <span className="text-xs">{incident.type.replace(/_/g, " ")}</span>
        </div>
      </div>

      {/* Key Info */}
      <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Info icon={MapPin} label="Site"     value={incident.site?.name ?? "-"} sub={incident.location ?? ""} />
        <Info icon={User}   label="Reporter" value={incident.reporter?.name ?? "-"} sub={incident.reporter?.role ?? ""} />
        <Info icon={Clock}  label="Occurred" value={formatDateTime(incident.occurredAt)} sub={timeAgo(incident.occurredAt)} />
        <Info icon={Siren}  label="Reported" value={formatDateTime(incident.reportedAt)} sub={timeAgo(incident.reportedAt)} />
      </div>

      {/* Description */}
      <Card className="glass mb-6">
        <CardHeader className="pb-3"><CardTitle className="text-sm">Description</CardTitle></CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed whitespace-pre-line">{incident.description}</p>
        </CardContent>
      </Card>

      {/* AI Analysis */}
      <Card className="glass mb-6">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-sm">
              <Brain className="h-4 w-4 text-primary" />
              AI Analysis
              <span className="text-[10px] font-normal text-muted-foreground">Powered by AEGIS</span>
            </CardTitle>
            <Button size="sm" variant="outline" onClick={runAnalysis} disabled={analyzing}>
              {analyzing ? (
                <><Loader2 className="mr-1.5 h-3 w-3 animate-spin" /> Analyzing...</>
              ) : (
                <><Brain className="mr-1.5 h-3 w-3" /> {ai ? "Re-analyze" : "Analyze"}</>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {analyzeErr && (
            <div className="mb-3 rounded-md border border-risk-critical/40 bg-risk-critical/5 p-2 text-xs text-risk-critical">
              {analyzeErr}
            </div>
          )}
          {!ai && !analyzing && (
            <div className="py-4 text-center text-sm text-muted-foreground">
              No analysis yet. Click &quot;Analyze&quot; to get hazards, root cause, and recommendations.
            </div>
          )}
          {ai && (
            <div className="space-y-4">
              {ai.summary && (
                <div className="rounded-md border border-primary/20 bg-primary/5 p-3">
                  <div className="text-[10px] uppercase tracking-wider text-primary">Executive Summary</div>
                  <p className="mt-1 text-sm leading-relaxed">{ai.summary}</p>
                </div>
              )}
              <div className="grid gap-4 sm:grid-cols-2">
                <AIList icon={AlertTriangle} label="Root Cause"          items={ai.rootCause ? [ai.rootCause] : []} tone="critical" />
                <AIList icon={TrendingUp}    label="Contributing Factors" items={ai.contributingFactors} tone="critical" />
                <AIList icon={Siren}         label="Immediate Actions"    items={ai.immediateActions}    tone="info" />
                <AIList icon={Shield}        label="Preventive Actions"   items={ai.preventiveActions}   tone="info" />
                <AIList icon={CheckCircle2}  label="Recommendations"      items={ai.recommendations}     tone="info" />
                <AIList icon={TrendingUp}    label="Predictions"          items={ai.predictions}         tone="critical" />
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Training Video Generation */}
      <Card className="glass mb-6">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-sm">
              <Clapperboard className="h-4 w-4 text-primary" />
              Training Video Generation
              <span className="text-[10px] font-normal text-muted-foreground">AGEIS</span>
            </CardTitle>
            <Button size="sm" variant="outline" onClick={generateVideo}
              disabled={video.status === "SUBMITTING" || video.status === "PROCESSING"}>
              {video.status === "SUBMITTING" || video.status === "PROCESSING" ? (
                <><Loader2 className="mr-1.5 h-3 w-3 animate-spin" /> {video.message}</>
              ) : (
                <><Clapperboard className="mr-1.5 h-3 w-3" /> {video.videoUrl ? "Regenerate" : "Generate Video"}</>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {video.status === "IDLE" && !video.videoUrl && (
            <div className="py-4 text-center text-sm text-muted-foreground">
              Generate an 8-second cinematic training video showing the correct safety response.
            </div>
          )}

          {video.status === "ERROR" && (
            <div className="rounded-md border border-risk-critical/40 bg-risk-critical/5 p-3 text-sm text-risk-critical">
              {video.message}
            </div>
          )}

          {video.videoPrompt && (
            <div className="mb-3 rounded-md border border-border/40 bg-muted/10 p-3">
              <div className="text-[10px] uppercase tracking-wider text-muted-foreground">AI Director Prompt</div>
              <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{video.videoPrompt}</p>
            </div>
          )}

          {video.videoUrl && (
            <video
              src={video.videoUrl}
              controls
              autoPlay
              className="w-full rounded-md border border-border/40"
            />
          )}
        </CardContent>
      </Card>

      {/* Auto-Generated Actions */}
      {incident.actions && incident.actions.length > 0 && (
        <Card className="glass mb-6">
          <CardHeader className="pb-3"><CardTitle className="text-sm">Action Items</CardTitle></CardHeader>
          <CardContent>
            <div className="space-y-2">
              {incident.actions.map((action) => (
                <div key={action.id} className="flex items-start gap-2 rounded-md border border-border/40 bg-muted/10 p-2">
                  <CheckCircle2 className={cn(
                    "h-3.5 w-3.5 mt-0.5",
                    action.completedAt ? "text-risk-low" : "text-muted-foreground"
                  )} />
                  <div className="flex-1 min-w-0">
                    <p className="text-xs">{action.description}</p>
                    <div className="mt-0.5 flex items-center gap-2 text-[10px] text-muted-foreground">
                      <span className="rounded-full border border-border/40 px-1.5 py-0.5">{action.status}</span>
                      {action.isAutoGenerated && (
                        <span className="rounded-full border border-primary/30 text-primary px-1.5 py-0.5">AI</span>
                      )}
                      {action.dueDate && <span>Due: {formatDateTime(action.dueDate)}</span>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function Info({ icon: Icon, label, value, sub }: {
  icon: typeof MapPin; label: string; value: string; sub?: string;
}) {
  return (
    <Card className="glass">
      <CardContent className="p-3">
        <div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-muted-foreground">
          <Icon className="h-3 w-3" />
          {label}
        </div>
        <div className="mt-1 text-sm font-medium">{value}</div>
        {sub && <div className="mt-0.5 text-[10px] text-muted-foreground">{sub}</div>}
      </CardContent>
    </Card>
  );
}

function AIList({ icon: Icon, label, items, tone }: {
  icon: typeof AlertTriangle; label: string; items?: string[]; tone: "critical" | "info";
}) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <div className={cn(
        "mb-1.5 flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider",
        tone === "critical" && "text-risk-critical",
        tone === "info"     && "text-primary"
      )}>
        <Icon className="h-3 w-3" />
        {label}
      </div>
      <div className="space-y-1">
        {items.map((item, i) => (
          <div key={i} className="flex items-start gap-1.5 rounded-md border border-border/40 bg-background/30 p-1.5 text-[11px]">
            <span className="text-[9px] text-muted-foreground mt-0.5">{i + 1}.</span>
            <span>{item}</span>
          </div>
        ))}
      </div>
    </div>
  );
}